### ISSUE TITLE
Compilation issue with Intel

### ISSUE THREAD

**Issue by settouati** [GEOS-DEV/GEOS#531]
**Describe the bug**
```
[ 27%] Building CXX object coreComponents/fileIO/CMakeFiles/fileIO.dir/silo/SiloFile.cpp.o
cd /data/pau915/SIM_RD/05_USERS/simon/workspace/geosx/GEOSX/build-pangea1_intel-release/coreComponents/fileIO && /data_local/sw/intel/impi/5.1.3.223/intel64/bin/mpiicpc   -I/data/pau915/SIM_RD/05_USERS/simon/workspace/geosx/GEOSX/src/coreComponents -I/data/pau915/SIM_RD/05_USERS/simon/workspace/geosx/GEOSX/src/coreComponents/cxx-utilities/src/src -I/data/pau915/SIM_RD/05_USERS/simon/workspace/geosx/GEOSX/build-pangea1_intel-release/include -I/data/pau915/SIM_RD/05_USERS/simon/workspace/geosx/GEOSX/src/coreComponents/linearAlgebraInterface/src -isystem /data/pau915/SIM_RD/05_USERS/simon/workspace/geosx/thirdPartyLibs/install-pangea1_intel-release/silo/include -isystem /data/pau915/SIM_RD/05_USERS/simon/workspace/geosx/thirdPartyLibs/install-pangea1_intel-release/hdf5/include -isystem /data_local/sw/intel/compilers_and_libraries_2016.3.223/linux/mpi/intel64/include -isystem /data/pau915/SIM_RD/05_USERS/simon/workspace/geosx/thirdPartyLibs/install-pangea1_intel-release/pugixml/include -isystem /data/pau915/SIM_RD/05_USERS/simon/workspace/geosx/thirdPartyLibs/install-pangea1_intel-release/raja/include -isystem /data/pau915/SIM_RD/05_USERS/simon/workspace/geosx/GEOSX/src/../../thirdPartyLibs/install-pangea1_intel-release/conduit/include/conduit -isystem /data/pau915/SIM_RD/05_USERS/simon/workspace/geosx/thirdPartyLibs/install-pangea1_intel-release/trilinos/include -isystem /data/pau915/SIM_RD/05_USERS/simon/workspace/geosx/GEOSX/src/../../thirdPartyLibs/install-pangea1_intel-release/axom/include -isystem /data/pau915/SIM_RD/05_USERS/simon/workspace/geosx/GEOSX/src/../../thirdPartyLibs/install-pangea1_intel-release/chai/include -isystem /data/pau915/SIM_RD/05_USERS/simon/workspace/geosx/thirdPartyLibs/install-pangea1_intel-release/axom/include/axom/slic -isystem /data/pau915/SIM_RD/05_USERS/simon/workspace/geosx/thirdPartyLibs/install-pangea1_intel-release/axom/include/axom/core -isystem /data/pau915/SIM_RD/05_USERS/simon/workspace/geosx/thirdPartyLibs/install-pangea1_intel-release/axom/include/axom/lumberjack -isystem /data/pau915/SIM_RD/05_USERS/simon/workspace/geosx/thirdPartyLibs/install-pangea1_intel-release/chai/include -isystem /data/pau915/SIM_RD/05_USERS/simon/workspace/geosx/thirdPartyLibs/install-pangea1_intel-release/mathpresso/include -isystem /data/pau915/SIM_RD/05_USERS/simon/workspace/geosx/thirdPartyLibs/install-pangea1_intel-release/conduit/include/conduit -isystem /data/pau915/SIM_RD/05_USERS/simon/workspace/geosx/thirdPartyLibs/install-pangea1_intel-release/axom/include/axom/sidre -isystem /data/pau915/SIM_RD/05_USERS/simon/workspace/geosx/thirdPartyLibs/install-pangea1_intel-release/axom/include/fmt -isystem /data/pau915/SIM_RD/05_USERS/simon/workspace/geosx/thirdPartyLibs/install-pangea1_intel-release/axom/include -isystem /data/pau915/SIM_RD/05_USERS/simon/workspace/geosx/GEOSX/src/thirdparty/optionparser/src -isystem /data/pau915/SIM_RD/05_USERS/simon/workspace/geosx/thirdPartyLibs/install-pangea1_intel-release/hypre/include -isystem /data/pau915/SIM_RD/05_USERS/simon/workspace/geosx/thirdPartyLibs/install-pangea1_intel-release/superlu_dist/include  -Wall -Wextra   -Werror  -O3 -DNDEBUG -fPIC   -std=c++14 -o CMakeFiles/fileIO.dir/silo/SiloFile.cpp.o -c /data/pau915/SIM_RD/05_USERS/simon/workspace/geosx/GEOSX/src/coreComponents/fileIO/silo/SiloFile.cpp
/data/pau915/SIM_RD/05_USERS/simon/workspace/geosx/GEOSX/src/coreComponents/fileIO/silo/SiloFile.cpp(1620): internal error: assertion failed at: "shared/cfe/edgcpfe/expr.c", line 33224

              newWrapper = fakeGroup.RegisterViewWrapper<arrayType>( fieldName );
                           ^

compilation aborted for /data/pau915/SIM_RD/05_USERS/simon/workspace/geosx/GEOSX/src/coreComponents/fileIO/silo/SiloFile.cpp (code 4)
make[2]: *** [coreComponents/fileIO/CMakeFiles/fileIO.dir/silo/SiloFile.cpp.o] Error 4
make[2]: Leaving directory `/data/pau915/SIM_RD/05_USERS/simon/workspace/geosx/GEOSX/build-pangea1_intel-release'
make[1]: *** [coreComponents/fileIO/CMakeFiles/fileIO.dir/all] Error 2
make[1]: Leaving directory `/data/pau915/SIM_RD/05_USERS/simon/workspace/geosx/GEOSX/build-pangea1_intel-release'
make: *** [all] Error 2
```

**To Reproduce**
Compile with Intel 18.0.3.222

**Expected behavior**
No compilation errors

**Platform (please complete the following information):**
- Platform: Linux x86_64
- OS: SUSE Linux Enterprise Server 11
- Kernel: 3.0.101-0.47.55-default
- CPU: Haswell 2.5GHz
- Compiler: intel-compxe/18.0.3.222
- MPI: intel-mpi/5.1.3.223
- CMake: cmake/3.13.1
