### PR TITLE
fix: Remove shadow declarations

### PR DESCRIPTION
**Pull request by dkachuma**
Trying to build with clang-17.0.4 issues errors of the form
```
CellBlockManager.cpp:252:13: error: declaration shadows a field of 'geos::FaceBuilder' [-Werror,-Wshadow]
```
This PR fixes this.

### CODE REVIEW

**Review by paveltomin — APPROVED** [review]

**Review by rrsettgast — APPROVED** [review]

**Review by rrsettgast — APPROVED** [review]

**Comment by CusiniM** [comment]
one of the CI jobs should have `clang17`...

**Review by CusiniM — APPROVED** [review]
